### ISSUE TITLE
Understanding Locking Logic for Redis

### ISSUE THREAD

**Issue by andrewboag** [matomo-org/plugin-QueuedTracking#99]
Hi team,

Firstly, great plugin. Has really helped with our matomo instance.

This is more a question than an issue. And happy for you to point us at code libraries, but wanted to understand the logic behind locking as it pertains to the redis queue. Why lock? What is the condition that is being mitigated?

Can you give us any background or a brief logical overview.

Cheers.

**Comment by tsteur** [comment]
You define a number of queues and only one worker at a time can work on one queue and the lock ensures that.

It's restricted to one worker per queue because it's important that requests are being processed in order. If two workers would take out tasks at the same time, then it would be possible that the second worker processes some of the tracking requests faster than the other which would result in tracking requests being processed out of order which could lead to wrong data issues.

If you have eg 10 queues, we make sure to put all requests from the same visitor into the same queue. Eg queue 5. And we want to make sure to process the tracking requests in the same order as they came in. Not eg the 3rd tracking request before the 2nd. 

Hope that somewhat helps.

**Comment by andrewboag** [comment]
Makes sense. Thanks.
